### ISSUE TITLE
Amplify init

### ISSUE THREAD

**Issue by matsuihidetoshi** [jaws-ug/jpk2024-broadcast-viewer#1]
# 概要
Amplify プロジェクトをスタートする

# 全体的な設計
- パブリックアクセス可能な Web サイトにするので、 Cognito その他による認証はなし
- そのため、AppSync の GraphQL エンドポイントは IAM 認証にする

# Tasks
- [ ] フロントエンドのライブラリ・フレームワークを決定する（多分ドキュメントの多さ的にシンプルな `create-react-app` の React アプリケーションで良いかも？お任せします）
- [ ] Gen2 で初期化
- [ ] 必要な初期設定等は相談しながら決定

**Comment by Yoshiitaka** [comment]
Githubと連携し、Amplify Gen2自体のinitと、自動Deploy処理は完了
下記が一旦のドメイン(東京リージョンに作成)
https://main.d2dla83fs9fiur.amplifyapp.com/
