### ISSUE TITLE
IVS の配信表示

### ISSUE THREAD

**Issue by matsuihidetoshi** [jaws-ug/jpk2024-broadcast-viewer#3]
# 概要
Amazon IVS の配信を表示する。
Video.js の IVS プラグインを使う必要がある。
Vue になっちゃうが、手順は [これ](https://aws.amazon.com/jp/builders-flash/202107/amplify-ivs-streaming-website)  とほぼ同等でできそう。
Real-time ではなく Low-latency の方でやる。

# Tasks
- [ ] Video.js + IVS のプラグインで実装する
  - 参考: https://docs.aws.amazon.com/ja_jp/ivs/latest/LowLatencyUserGuide/player-videojs.html
- [ ] もしかしたら wasm モジュールをうまく引っ張ってこれないかもしれないので、その場合 CopyWebpackPlugin を使う（そもそも Vite とか使ってる場合はそれに準じた方法）
  - 参考: https://github.com/matsuihidetoshi/jawsdays2021ivshead/blob/97657a187a57d0899320189539c2ebaeab1b5e07/nuxt.config.ts#L125-L134
  - どうしても厳しかったら Dom 操作とかで AWS 側でサンプルとして提供されている生の JS タグを読み込む形で良い

**Comment by Yoshiitaka** [comment]
このサンプルがかなり優秀で使えそうです。
https://github.com/aws-samples/amazon-ivs-broadcast-web-demo/tree/main

**Comment by Yoshiitaka** [comment]
Done。wasm モジュールをnode_moduleから引けなかったので、直接梱包し、参照するようにしています。
